"""create learning sessions

Revision ID: 414cf7cbbed1
Revises:
Create Date: 2025-11-10 19:09:05.594299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '414cf7cbbed1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Check if table already exists before creating
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    if 'learning_sessions' not in inspector.get_table_names():
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('learning_sessions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('difficulty', sa.String(length=50), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        # ### end Alembic commands ###
    else:
        print("ℹ️  Table 'learning_sessions' already exists, skipping creation")


def downgrade() -> None:
    """Downgrade schema."""
    # Check if table exists before dropping
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    if 'learning_sessions' in inspector.get_table_names():
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table('learning_sessions')
        # ### end Alembic commands ###
    else:
        print("ℹ️  Table 'learning_sessions' does not exist, skipping drop")
